### PR TITLE
rewrote sidebar search

### PR DESCRIPTION
**Pull request by doebi**
I fixed the broken search in the sidebar.

changes:
- no event bubbling to App.vue
- reactive update through computed list
- empty categories are not displayed anymore
- no redundant information in config.json

Important Notes:
the config.json is not fully updated yet. Some modules still have category=null.

The direct navigation is disabled, but this is broken anyway according to: https://github.com/Turfjs/turf-www/issues/121

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @doebi 

I didn't think the search was broken, it was functioning as I'd intended :) I'll try and take a look over the next few days

**Comment by DenisCarriere** [comment]
👍 @doebi I do support this change, I also didn't like the search which showed all the categories, it was very hard to show someone what the result was when 10+ categories were in the way of the expected result.

These commits look good 👍

@rowanwins feel free to jump in afterwards.

**Comment by DenisCarriere** [comment]
👍 I like it, however now all the modules are now defined as `Null` category... would there be a way to leverage the [`documentation.yml`](https://github.com/Turfjs/turf-www/blob/master/documentation.yml) to determine the module categories? This could easily be converted to JSON to make it easy to read/parse in Vue.

image

**Comment by DenisCarriere** [comment]
@rowanwins This update isn't live yet, we still need to publish the `build.js` to the master branch, so have a final look at it before we push these changes.

@doebi If you can figure out a good solution to change the Modules to their Category, then feel free to push the new `build.js` and I can merge it 👍

**Pull request merged**
