### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by twelch**
Add changelog link, update typedef needs.

### CODE REVIEW

**Comment by twelch** [comment]
@smallsaucepan, can you tell me how work gets merged to gh-pages for deployment after.  Thanks!

**Comment by twelch** [comment]
#196 looks like it might be relevant.  The types change here is specific to v7.

**Comment by smallsaucepan** [comment]
What do you think about an "upgrade guide", separate to getting started?

**Comment by twelch** [comment]
Yeah I'll add a separate page

**Comment by twelch** [comment]
Okay, I took a shot at it @smallsaucepan.

**Comment by twelch** [comment]
I assume 6.5 docs have already been snapshotted and this would become part of v7 "latest" docs

**Comment by smallsaucepan** [comment]
Yes, I'm about to snapshot v7, so that drop down will end up having:

- Next
- 7.0.0 (a.k.a current and the default people will see when they visit)
- 6.5.0
- All versions

**Review by smallsaucepan — APPROVED** [review]

**Pull request merged**
