### PR TITLE
Docs overhaul

### PR DESCRIPTION
**Pull request by rowanwins**
Gday,

As per the discussion in #91 I've had a go at redoing the turf docs 

A few notes
- I've included npm install tags in the API documentation which is helpful for the camel casing/hyphens of module names and things like turf/helpers
- The cdn links now reference https://npmcdn.com/@turf/turf/turf.min.js which automatically redirects people to the most recent version so that's handy
-- On a side note I wonder if it's worth adding a version number to the turf.js just by importing the package number (similar to what leaflet has)?
- The docs now have a consistent theme across all pages and are navigable across all pages
- I've also done a fairly major tidy up of files in the repo and tried to improve the repo doco for contributing.

Below are a few screengrabs
alt tag
alt tag
alt tag
alt tag

Still some things to tidy up but I reckon they are an improvement.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks @rowanwins for taking the time to create this PR, these changes are a lot to process and I'm not to familiar with `turf-www`. Might need some valuable input from @lyzidiamond or @tmcw.

**Comment by DenisCarriere** [comment]
Ops.. can't merge anymore because of conflicts.

@rowanwins can you look into resolving these files:

```
.gitignore
docs/index.html
index.html
package.json
```

I'm going to assume that @morganherlocker looked over the new proposed style and approved it by his ❤️ .

It looks good to me as well 👍

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Merge conflicts all resolved now so fingers crossed it's all good now. 

I've got a few ideas for a new homepage design so once we get these changes in I'll get around to taking a stab at that I figured I'd start with the important stuff first.

Cheers

**Comment by DenisCarriere** [comment]
@rowanwins Looks good, there was no objections this week about it. 👍

**Comment by DenisCarriere** [comment]
@rowanwins It's live! Looks good from what I've seen so far! I believe you were mentioning having interactive maps in the `@examples`, that visual explanation would be really cool!

**Comment by tmcw** [comment]
Sorry I've been offline for a bit (I live in DC and the bad stuff with that damn guy keeps coming up).

_This is incredible._ Amazing work @rowanwins! Visually and structurally this is such a big improvement.

**Pull request merged**
