### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by stebogit**
@DenisCarriere @rowanwins 
I corrected the @examples in `@turf` (PR [#857](https://github.com/Turfjs/turf/pull/857) and [commit 86f3c2](https://github.com/Turfjs/turf/commit/86f3c24413dcf8a7a9a5ddc974b54ea3ebe4a7d2)) and ran `npm run deploy`, plus fixed few typos in the doc here.

Should I also add the new functions/modules to `documentation.yml`?

This PR contain also the updates for the www pages, generated by the `deploy`, am I right?

### CODE REVIEW

**Comment by rowanwins** [comment]
Gday @stebogit 

Yep that all looks fine to me so far, and yep you're right this does include the files from `npm run deploy` (the index.html and the static assets like the generated js and css). 

I think you may as well add in the new modules and do it all in one hit.

**Comment by DenisCarriere** [comment]
👍 to include the new modules, it will move along publishing the release if we see them in the Docs.

**Comment by DenisCarriere** [comment]
@stebogit Noticed the `assets` folder was nested, seems strange, don't know what caused that:

image

**Comment by stebogit** [comment]
I think I did all the necessary to update the website.
I added all the new modules, which now fail running the examples; I guess this will be fixed when we'll publish the next release with those modules.

**Comment by DenisCarriere** [comment]
@stebogit 👍 nice work!

**Pull request merged**
