### PR TITLE
Fixed broken URLs

### PR DESCRIPTION
**Pull request by Timtech4u**
Fixed broken URLS:
- Intro to Turf
- Analysis with Turf

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @Timtech4u 

This ideally needs to be done in the [`Getting-Started.vue` file in the src folder](https://github.com/Turfjs/turf-www/blob/master/src/pages/Getting-Started.vue) otherwise these changes will get overridden.

Give us a yell if you get stuck

**Comment by Timtech4u** [comment]
> Hi @Timtech4u
> 
> This ideally needs to be done in the [`Getting-Started.vue` file in the src folder](https://github.com/Turfjs/turf-www/blob/master/src/pages/Getting-Started.vue) otherwise these changes will get overridden.
> 
> Give us a yell if you get stuck

Yes, definitely! I'll re-open a new PR for this :+1:

**Comment by Timtech4u** [comment]
@rowanwins  this has been fixed already by #145 , I think a build & deployment is what's needed.

**Comment by rowanwins** [comment]
Yeah I think you're right!

**Pull request closed without merging**
