### PR TITLE
Add Automated Testing to API Docs

### PR DESCRIPTION
**Pull request by jvrousseau**
This adds some basic testing of the /static/docs routes of the website. 

The test does the following:
- check for JavaScript Errors from each page
- check that all page resources load properly
- renders a screen shot of the page as a png

This could help you all out with testing #81 along with catching any regressions that pop up between releases.

@morganherlocker, please let me know if there is anything I could change that would make this more useful for the project.

Thanks!
Jordan

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@jvrousseau This is unfortunate that this PR has not be merged or commented on. I'm not to familiar with `turf-www` to confidently be able to merge this.

Thanks for your contributions! Hopefully someone else can weigh in here.

**Comment by morganherlocker** [comment]
Somehow I missed the first notification on this PR, but thanks for bumping @DenisCarriere. This is a really good idea and would have saved many "doh" moments in the past with a broken example here and there, which frequently sneak into a release. I'll give this a spin and review.

**Comment by DenisCarriere** [comment]
@morganherlocker Awesome, yes this PR looks very useful for automated deployments.

**Comment by jvrousseau** [comment]
@DenisCarriere wow! I forgot this was still hanging out there.

My intentions were to test the individual pages that housed live map examples. Since the docs are now generated via [documentationjs](https://github.com/documentationjs), there would need to be ~~some~~ _a lot of_ changes to be comfortable with the test coverage. I would love to take the opportunity to hash out some concepts in www such that those "doh" moments are covered **_and_** we don't have to look at my old code 🙈 

A couple of thoughts:

- The examples found in documentation could be tested. That way it could be ensured that a copy/paste from the docs are successful. 

- The generated HTML pages could be tested for browser errors (similar to what I was doing in this PR) and screen captures (very nice for future PRs).

- If map or visualization examples are added to the docs (comment via #91), the HTML testing would be very beneficial.

I think I will start to look at pulling in the examples found in documentation for testing. However, if you or any turf folk have another testing path that you would like to see traversed, please let me know!

Thanks,
Jordan

**Comment by DenisCarriere** [comment]
@jvrousseau This sounds like a perfect plan, having tests on the `@example` would be very beneficial! I know that Morgan said he was going to look at this as well, anything that makes automatic deployments run smoother is a big 👍 !

Looking forward to some new commits/PRs on this topic.

**Pull request closed without merging**
