### PR TITLE
Reintroduce examples

### PR DESCRIPTION
**Pull request by rowanwins**
Gday @DenisCarriere & @morganherlocker 

This request include the code I have for reintroducing the example maps back into the API page in the simplest manner I can find.
- If a modules doesnt have the `@exampleFeaturesToAddToMap` then no map get's rendered. 
- The `@exampleFeaturesToAddToMap` is an comma delimited string of all the feature variables names to add to the map, these variable names have to be in the `@example` code snippet
- I add a popup to each feature containing the properties where they exist (eg for the collect module this is relevant)

Anyway it's the best I can come up with so far

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@rowanwins Need to resolve conflicts, occurred from the last merge.

**Comment by rowanwins** [comment]
Gday @DenisCarriere  (cc @tmcw as guru of all things documentation.js & jsdoc)

Just looking to get this moving again. There are three main parts to consider

1. In the jsdoc for a module we'd add a new tag called `exampleFeaturesToAddToMap` which would refer down to the example tag, so for example the `turf/along` module would look like 
````
/**
 * Takes a {@link LineString|line} and returns a {@link Point|point} at a specified distance along the line.
 *
 * @name along
 * @param {Feature<LineString>} line input line
 * @param {number} distance distance along the line
 * @param {string} [units=kilometers] can be degrees, radians, miles, or kilometers
 * @return {Feature<Point>} Point `distance` `units` along the line
 * @exampleFeaturesToAddToMap line, along
 * @example
 * var line = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "LineString",
 *     "coordinates": [
 *       [-77.031669, 38.878605],
 *       [-77.029609, 38.881946],
 *       [-77.020339, 38.884084],
 *       [-77.025661, 38.885821],
 *       [-77.021884, 38.889563],
 *       [-77.019824, 38.892368]
 *     ]
 *   }
 * };
 *
 * var along = turf.along(line, 1, 'miles');
 *
 * var result = {
 *   "type": "FeatureCollection",
 *   "features": [line, along]
 * };
 *
 * //=result
 */
````
2. [This bit](https://github.com/rowanwins/turf-www/blob/0d90a7833693dc852b5c6412b3f089ea350a4962/template/turf_2017/section._#L3-L14) in the documentation.js template means that if we find the relevant tag we'll render a map for that module
3. [This chunk](https://github.com/rowanwins/turf-www/blob/0d90a7833693dc852b5c6412b3f089ea350a4962/template/turf_2017/index.js#L32-L44) takes the jsdocs tag that I'm proposing to introduce and converts it to a mapbox.js snippet to create it as a layer to display on the map.

I'd also introduce a [layer control](http://leafletjs.com/reference-1.0.3.html#control-layers) so that people could toggle layers on and off which may help to make things a bit clearer.

Anyway that's a summary of where I've got to, for more info discussion check out [this issue](https://github.com/Turfjs/turf-www/issues/50). And it would look something like
IProgress

Cheers
Rowan

**Comment by DenisCarriere** [comment]
Anyways we could simply use the `//=` tags.

You could also extract **Before** & **After** by finding the `//=` tags that are before a `turf.<module>` and anything after.

If only `//=results` is provided, then a single map is created, if both Before & After are supplied, then two maps are created.

We don't need to make the Leaflet/Mapbox maps complicated, just needs to display the GeoJSON.

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Im not sure how viable it is to use the `//=` as they are quite variable.
- Sometimes the `//=` references a feature collection which contains both the input and output poly, eg [turf/centroid](https://github.com/Turfjs/turf/blob/master/packages/turf-centroid/index.js#L31-L36)
- Other time the `//=` simply reference the outut eg [turf/circle](https://github.com/Turfjs/turf/blob/master/packages/turf-circle/index.js#L22)
- I can't see any modules where there is a `//=` before the module call

**Comment by DenisCarriere** [comment]
@rowanwins Well it's not that random since we can always change the JSDocs. We could always simply create 1 map using all the `//=` tags. I just don't really like having a JSDocs attribute that isn't "standard" like you were mentioning with `exampleFeaturesToAddToMap`, creating a map seems possible with simple `//=` tags, makes the JSDocs look cleaner.

Bottom line, we need a map! 👍

**Comment by DenisCarriere** [comment]
Merged this PR from https://github.com/Turfjs/turf-www/pull/105 (might need some more work).

**Pull request closed without merging**
